SNIPPETS = [
"""def factorial(n):\n    r=1;\n    for i in range(2,n+1): r*=i+i%2\n    s=str(r); print(n,len(s),s[-5:])\nprint(factorial(10))""",
"""def fib_series(k):\n    a,b=0,1; seq=[];\n    while len(seq)<k: seq.append(a); a,b=b,a+b\n    tail=sum(seq[-3:]); print(len(seq),tail,seq[:5])\nprint(fib_series(15))""",
"""def chunk(xs,m):\n    out=[xs[i:i+m] for i in range(0,len(xs),m)]\n    flat=sum(len(c) for c in out); print(len(out),flat,out[0])\nprint(chunk(list(range(23)),5))""",
"""def normalize(nums):\n    mx=max(nums); mn=min(nums); span=mx-mn if mx!=mn else 1; out=[(x-mn)/span for x in nums]; print(out[:4],mx,mn)\nprint(normalize([3,7,1,9,4,6]))""",
"""def binary_search(a,t):\n    lo,hi=0,len(a)-1; steps=0\n    while lo<=hi:\n        mid=(lo+hi)//2; steps+=1;\n        if a[mid]==t: print(mid,steps,a[mid]); break\n        if a[mid]<t: lo=mid+1\n        else: hi=mid-1\n    else: print(-1,steps)\nprint(binary_search(list(range(0,60,3)),30))""",
"""def rotate_left(xs,k):\n    k%=len(xs) if xs else 0; r=xs[k:]+xs[:k]; print(r[:5],len(r))\nprint(rotate_left(list(range(20)),7))""",
"""def dedupe_stable(xs):\n    seen=set(); out=[];\n    for x in xs:\n        if x not in seen: seen.add(x); out.append(x)\n    print(len(out),out[:6])\nprint(dedupe_stable([1,2,1,3,2,4,5,4,6,7,7,8]))""",
"""def vowel_map(text):\n    low=text.lower(); m={c:low.count(c) for c in 'aeiou'}; total=sum(m.values()); print(m,total)\nprint(vowel_map('Concatenation Example'))""",
"""def transpose(mat):\n    t=[list(r) for r in zip(*mat)]; flat=sum(sum(r) for r in t); print(len(t),flat,t[0])\nprint(transpose([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]))""",
"""def sliding_sum(nums,k):\n    if k<=0: print([]);\n    cur=sum(nums[:k]); out=[cur];\n    for i in range(k,len(nums)): cur+=nums[i]-nums[i-k]; out.append(cur)\n    print(out[:5],len(out))\nprint(sliding_sum(list(range(30)),5))""",
"""def groups_of_pairs(xs):\n    out=[(xs[i],xs[i+1]) for i in range(0,len(xs)-1,2)]; print(out[:4],len(out))\nprint(groups_of_pairs(list(range(25))))""",
"""def multiply_mats(a,b):\n    rows=len(a); cols=len(b[0]); res=[[0]*cols for _ in range(rows)]\n    for i in range(rows):\n        for j in range(cols):\n            for k in range(len(b)): res[i][j]+=a[i][k]*b[k][j]\n    print(res[0][:3],rows,cols)\nprint(multiply_mats([[1,2,3],[4,5,6]],[[1,0],[0,1],[1,1]]))""",
"""def prefix_sums(xs):\n    out=[]; acc=0;\n    for v in xs: acc+=v; out.append(acc)\n    print(acc,out[-2:],len(out))\nprint(prefix_sums([3,1,4,1,5,9,2,6,5]))""",
"""def count_substring(s,sub):\n    c=s.count(sub); r=s.replace(sub,''); print(c,len(r),r[:6])\nprint(count_substring('ababababab','ab'))""",
"""def pad_center(s,w):\n    d=w-len(s); left=d//2; right=d-left; out=' '*left+s+' '*right; print(len(out),out[:5])\nprint(pad_center('title',20))""",
"""def range_pairs(n):\n    r=[(i,i*i) for i in range(n)]; tail=sum(v for _,v in r[-5:]); print(len(r),tail,r[0],r[-1])\nprint(range_pairs(25))""",
"""def encode_numbers(xs):\n    s=':'.join(str(x) for x in xs); z=s.split(':'); print(len(z),z[0],z[-1])\nprint(encode_numbers([5,10,15,20,25,30,35,40]))""",
"""def window_pairs(xs,k):\n    out=[xs[i:i+k] for i in range(len(xs)-k+1)]; print(len(out),out[0],out[-1])\nprint(window_pairs(list(range(18)),3))""",
"""def invert_map(m):\n    r={v:k for k,v in m.items()}; keys=sorted(r.keys()); print(keys[:3],len(keys))\nprint(invert_map({'a':1,'b':2,'c':3,'d':4}))""",
]
